### ISSUE TITLE
Lots of typos

### ISSUE THREAD

**Issue by xogeny** [xogeny/ModelicaBook#163]
This list is from Tim Nye (via email):

In http://book.xogeny.com/components/components/elec_comps/
   - [x] StepVoltage code is missing its equations. #271 

In http://book.xogeny.com/components/components/rot_comps_basic/
- [x] Broken image for Inertia, Spring and Damper models.
- [x] Code for Damper has highlight, but not Inertia and Spring
- [x] Mechanical Ground code is wrong.

In http://book.xogeny.com/components/components/rot_comps_adv/
- [x] might be helpful in backlash equations to say that c is a torsional stiffness (does having it prevent numerical problems?) and that delta phi is "phi_rel" in the code.
- [X] "An equation to constrains the motion" --> "An equation to constrain the motion"~~
- [x] In "Simulate SMD_WithGroundedGear" inertia3 needs to be set to 2.6 for the responses to match, i.e., i3 = i2 + R^2 * i1 (reflected inertia).

In http://book.xogeny.com/components/components/population/
- [x] Icon images are broken

In http://book.xogeny.com/components/components/speed_comps/
- [ ]  being picky, in SampleHold code, sample_rate is actually a sample_time. See #308
- [X] "Behaviorally, there is not difference" --> "Behaviorally, there is no difference"

In http://book.xogeny.com/components/components/block_comps/
- [x] first two icon images are broken.
- [x] the schematic for the Thermal Control example doesn't have the connections drawn in.

In http://book.xogeny.com/components/components/chem_comps/
- [X] first line is "o.. _chem-components:"
- [ ] the variable R in Mixture appears to be a vector containing the concentration rates of the three species A, B and X. Later, in X+B->R+S, R is described as an intermediate species. See #310
- [x] "#.. plot:: ../plots/ABX.py # :include-source: no" is before Conclusion.

In http://book.xogeny.com/components/components/component_models/
- [X] In Generated Equations and Conservation, "ground.flange_a.phi = damper2.flange_b;" --> "ground.flange_a.phi = damper2.flange_b.phi;" and "damper2.flange_b.phi = spring2.flange_b;" --> "damper2.flange_b.phi = spring2.flange_b.phi;" #272

In http://book.xogeny.com/components/subsystems/gear/
- [X]  "in a model of something like an automotive transmission model." --> "in a model of something like an automotive transmission."

In http://book.xogeny.com/components/subsystems/population/
- [X] in model Migration, "fox_a.rate + fox_b.rate = 0 "Conservation of rabbits";" --> foxes.

In http://book.xogeny.com/components/subsystems/power_supply/
- [X] below Simulate FlatCircuit: "(because the load connecting the switch to the power supply is open)" --> "(because the switch to the power supply is open)"
- [x] in model BasicPowerSupply, no values are given for Lm1, C and n. Also, Goff and Ron are added to the diodes, but the conclusion for the output is "Using our hierarchical system model we get, as expected, exactly the same results as we got for the flat version:".  Should Goff and Ron be removed to have the same model?

In http://book.xogeny.com/components/subsystems/heat_transfer/
(All still open issues in this part moved to #311)
- [x] a connection to wall2 is missing in the Flat System diagram.
- [ ] could a real example be added to help comprehension, for instance, a metal rod (C1-3) with a plastic cover (wall1-3)?  Or have convection at the walls?
- [ ]  maybe a description of why a lumped model is used, i.e., no PDEs in Modelica?
- [ ]  the Flat System simulation looks like it might have a discontinuity at t ~ 0.95s
- [X] in model Rod, "Thermal conductivie of rod" --> "Thermal conductivity of rod"~~ 
- [x]  "Modelica.Thermal.HeatTransfer.Interfaces.HeatPort_a ambient "Thermal connector for rod end 'a'" --> "Thermal connector to ambient"
- [ ]  I don't think the "import HTC=Modelica.Thermal.HeatTransfer.Components;" and "HTC.HeatCapacitor" shorthand has been described before.
- [ ]  "`HTC.ThermalConductor rod_conduction[n-1](each final G=G_rod)`" --> G=G_rod*n  i.e., each thinner slice of the rod conducts heat that much faster.  This is why the final graph shows the more segments, the less heat making it to the end of the rod.

In http://book.xogeny.com/components/subsystems/pendulums/
- [ ]  maybe say a bit about the MultiBody library?, e.g., why the r vectors and World component, where the animation comes from? See #312

In http://book.xogeny.com/components/subsystems/modifications/
- [x]  "a literal array (e.g., {24,24,24}, " --> ,24}),
- [x]  "we could use the :ref:`fill-function function:"

In http://book.xogeny.com/components/architectures/sensor_comparison/
- [x]  " Similarly, the purple box identifies the actuator." --> red box
- [x]  "Now, we want to create a variation of this model where the sensor component"  end of sentence?
- [x]  model IdealSensor code is repeated
- [ ]  can "redeclare" be used when instantiating classes, not just when extending them? See #313
- [ ]  general comment: stripping annotations out of code would improve readability. See #37

In http://book.xogeny.com/components/architectures/sensor_comparison_ad/
- [ ]  it would be nice to have diagrams beside each model code. See #314
- [x]  "Furthermore, if take some time" --> "Furthermore, if we take some time"

In http://book.xogeny.com/components/architectures/thermal_control/
- [x]  "sensor will be a temperature sense" --> sensor
- [x]  "Here we see the same basic pieces was saw in the previous section" --> pieces we saw
- [x]  "On some cases," --> "In some cases,"
- [ ]  a general proofreading of the page would be helpful. See #315

**Comment by xie-dongping** [comment]
In http://book.xogeny.com/components/components/elec_comps/

* StepVoltage code is missing its equations.

In http://book.xogeny.com/components/components/rot_comps_basic/

* Broken image for Inertia, Spring and Damper models.
* Code for Damper has highlight, but not Inertia and Spring
* Mechanical Ground code is wrong.

In http://book.xogeny.com/components/components/rot_comps_adv/

* might be helpful in backlash equations to say that c is a torsional stiffness (does having it prevent numerical problems?) and that delta phi is "phi_rel" in the code.
* ~~"An equation to constrains the motion" --> "An equation to constrain the motion"~~
* In "Simulate SMD_WithGroundedGear" inertia3 needs to be set to 2.6 for the responses to match, i.e., i3 = i2 + R^2 * i1 (reflected inertia).

In http://book.xogeny.com/components/components/population/

* Icon images are broken

In http://book.xogeny.com/components/components/speed_comps/

* being picky, in SampleHold code, sample_rate is actually a sample_time.
* ~~"Behaviorally, there is not difference" --> "Behaviorally, there is no difference"~~

In http://book.xogeny.com/components/components/block_comps/

* ~~first two icon images are broken.~~ already fixed
* the schematic for the Thermal Control example doesn't have the connections drawn in.

In http://book.xogeny.com/components/components/chem_comps/

* ~~first line is "o.. _chem-components:"~~
* the variable R in Mixture appears to be a vector containing the concentration rates of the three species A, B and X. Later, in X+B->R+S, R is described as an intermediate species.
* "#.. plot:: ../plots/ABX.py # :include-source: no" is before Conclusion.

In http://book.xogeny.com/components/components/component_models/

* In Generated Equations and Conservation, "ground.flange_a.phi = damper2.flange_b;" --> "ground.flange_a.phi = damper2.flange_b.phi;" and "damper2.flange_b.phi = spring2.flange_b;" --> "damper2.flange_b.phi = spring2.flange_b.phi;"

~~In http://book.xogeny.com/components/subsystems/gear/~~

* ~~"in a model of something like an automotive transmission model." --> "in a model of something like an automotive transmission."~~

~~In http://book.xogeny.com/components/subsystems/population/~~

* ~~in model Migration, "fox_a.rate + fox_b.rate = 0 "Conservation of rabbits";" --> foxes.~~

In http://book.xogeny.com/components/subsystems/power_supply/

* below Simulate FlatCircuit: "(because the load connecting the switch to the power supply is open)" --> "(because the switch to the power supply is open)"
* in model BasicPowerSupply, no values are given for Lm1, C and n. Also, Goff and Ron are added to the diodes, but the conclusion for the output is "Using our hierarchical system model we get, as expected, exactly the same results as we got for the flat version:". Should Goff and Ron be removed to have the same model?

In http://book.xogeny.com/components/subsystems/heat_transfer/

* a connection to wall2 is missing in the Flat System diagram.
* could a real example be added to help comprehension, for instance, a metal rod (C1-3) with a plastic cover (wall1-3)? Or have convection at the walls?
* maybe a description of why a lumped model is used, i.e., no PDEs in Modelica?
* the Flat System simulation looks like it might have a discontinuity at t ~ 0.95s
* ~~in model Rod, "Thermal conductivie of rod" --> "Thermal conductivity of rod"~~
* "Modelica.Thermal.HeatTransfer.Interfaces.HeatPort_a ambient "Thermal connector for rod end 'a'" --> "Thermal connector to ambient"
* I don't think the "import HTC=Modelica.Thermal.HeatTransfer.Components;" and "HTC.HeatCapacitor" shorthand has been described before.
*     "HTC.ThermalConductor rod_conductionn-1" --> G=G_rod*n i.e., each thinner slice of the rod conducts heat that much faster. This is why the final graph shows the more segments, the less heat making it to the end of the rod.

In http://book.xogeny.com/components/subsystems/pendulums/

* maybe say a bit about the MultiBody library?, e.g., why the r vectors and World component, where the animation comes from?

~~In http://book.xogeny.com/components/subsystems/modifications/~~

* ~~"a literal array (e.g., {24,24,24}, " --> ,24}),~~
* ~~"we could use the :ref:`fill-function function:"~~ non-error

In http://book.xogeny.com/components/architectures/sensor_comparison/

* ~~" Similarly, the purple box identifies the actuator." --> red box~~
* ~~"Now, we want to create a variation of this model where the sensor component" end of sentence?~~
* ~~model IdealSensor code is repeated~~
* can "redeclare" be used when instantiating classes, not just when extending them?
* general comment: stripping annotations out of code would improve readability.

In http://book.xogeny.com/components/architectures/sensor_comparison_ad/

* it would be nice to have diagrams beside each model code.
* ~~"Furthermore, if take some time" --> "Furthermore, if we take some time"~~

In http://book.xogeny.com/components/architectures/thermal_control/

* ~~"sensor will be a temperature sense" --> sensor~~
* ~~"Here we see the same basic pieces was saw in the previous section" --> pieces we saw~~
* ~~"On some cases," --> "In some cases,"~~
* a general proofreading of the page would be helpful.

**Comment by dietmarw** [comment]
In http://book.xogeny.com/components/components/block_comps/
 * ~~the schematic for the Thermal Control example doesn't have the connections drawn in.~~  fixed in 4fd69e86da7e739082cc29f788a631f8b1cfa234

**Comment by dietmarw** [comment]
Broken Icon issue is something that needs to be handled differently all together: #257

**Comment by dietmarw** [comment]
OK so I've fixed a couple of the listed issues in #309 and the rest were moved to respective tickets so they can be dealt with individually. This means this ticket can be closed for the sake of those other tickets.
